server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.114.150.179:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"